Declare "x" (Constant 150)
    (Declare "y" (Constant 200)
        (Seq (While (Greater (Variable "x" ) (Constant 0)
                    )
                    (Seq (Assign "x" (Minus (Variable "x")
                                            (Constant 1)
                                     )
                         )
                         (Assign "y" (Minus (Variable "y")
                                            (Constant 1)
                                     )
                         )
                    )
                )
                (Print (Variable "y"))
        )
    )
